// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 02/07/2026 14:02:06
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/Users/Antonin/Documents/LoLoChallenges/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Antonin/Documents/LoLoChallenges/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Antonin/Documents/LoLoChallenges/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Antonin/Documents/LoLoChallenges/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Antonin/Documents/LoLoChallenges/frontend/plugins/**/*.{js,ts,mjs}","C:/Users/Antonin/Documents/LoLoChallenges/frontend/composables/**/*.{js,ts,mjs}","C:/Users/Antonin/Documents/LoLoChallenges/frontend/utils/**/*.{js,ts,mjs}","C:/Users/Antonin/Documents/LoLoChallenges/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Antonin/Documents/LoLoChallenges/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Antonin/Documents/LoLoChallenges/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Antonin/Documents/LoLoChallenges/frontend/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;